// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsfdl0gxHJskTVL4jmsRTXx4i3aJW7hOA',
    appId: '1:679269700660:web:22bdbc74e9c34ab1fe6661',
    messagingSenderId: '679269700660',
    projectId: 'fir-authentication-73e9f',
    authDomain: 'fir-authentication-73e9f.firebaseapp.com',
    storageBucket: 'fir-authentication-73e9f.firebasestorage.app',
    measurementId: 'G-8YSPBVR4RR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOoAKkhb1psNkRELcV6SPUcOfhsest0Rs',
    appId: '1:854799983216:android:00f4b6083f77e3982f8ab5',
    messagingSenderId: '854799983216',
    projectId: 'inclass14-6d19c',
    storageBucket: 'inclass14-6d19c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbqC702Z8T_eMmqxG17tJNWq97lurLauY',
    appId: '1:679269700660:ios:d761bfe49b14f4bafe6661',
    messagingSenderId: '679269700660',
    projectId: 'fir-authentication-73e9f',
    storageBucket: 'fir-authentication-73e9f.firebasestorage.app',
    iosBundleId: 'com.example.themeDemo',
  );
}
